CREATE TABLE IF NOT EXISTS sensor (
  "id" SERIAL,
  "name" VARCHAR(32) NOT NULL,
  "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "deleted" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT sensor_pkey PRIMARY KEY(id)
);