CREATE TABLE IF NOT EXISTS sensor (
  "id" SERIAL,
  "name" VARCHAR(32) NOT NULL,
  "firmwareVersion" VARCHAR(16) NOT NULL,
  "mountHeight" INTEGER NOT NULL,
  "businessStartTime" TIME WITH TIME ZONE NOT NULL,
  "businessEndTime" TIME WITH TIME ZONE NOT NULL,
  "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "deleted" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT sensor_pkey PRIMARY KEY(id)
);