CREATE TABLE Location (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(32) NOT NULL,
    "address" VARCHAR(128) NOT NULL,
    "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE Device (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(32) NOT NULL,
    "locationId" INTEGER NOT NULL,
    "active" BOOLEAN DEFAULT TRUE,
    "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted" TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY ("locationId") REFERENCES Location("id") ON DELETE CASCADE
);

CREATE TABLE Count (
    "id" SERIAL PRIMARY KEY,
    "sensorId" INT NOT NULL,
    "timestamp" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "in" INT NOT NULL,
    "out" INT NOT NULL,
    FOREIGN KEY ("sensorId") REFERENCES Device("id") ON DELETE CASCADE
);